export const Errors = {
    PASSWORD_CONFIRMATION_ERROR: 'PASSWORD_CONFIRMATION_ERROR',
    USER_EXISTS: 'USER_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
};